spring:
  application:
    name: app-sample-produtos
  output.ansi.enabled: ALWAYS

  profiles:
    active:
      - debug-mode
      - h2

  http.encoding:
    charset: UTF-8
    enabled: true
    force: true
  jackson:
    time-zone: Brazil/East
    locale: pt_BR
    default-property-inclusion: non_null
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat

---
spring.profiles: debug-mode
logging.level:
  com.github.eltonsandre: debug
  org.springframework:
    cache: debug
    web: debug

---
server.port: 80
spring:
  profiles: docker
  datasource:
    username: root
    url: jdbc:mysql://mysql:3306/mydb?useSSL=false

---
spring:
  profiles: h2
  datasource:
    platform: h2
    initialization-mode: always
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/database;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa

  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect